[package]
name = "uppies"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
surge-ping = "0.8.2"
tokio = { version = "1.46.1", features = ["full"] }
